version: 0.2

phases:
  install:
    commands:
      - curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
      - apt install -y nodejs
      - npm install -g npm

  pre_build:
    commands:
      - npm install

  build:
    commands:
      - npm run build
      - ls

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build